name: Deploy API

on:
  push:
    branches:
      - main  # Déclenchement sur chaque push dans la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Exécuter le workflow sur une machine virtuelle Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone le code du repo GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Définit la version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}  # IP du serveur (défini dans GitHub Secrets)
          SSH_USER: ${{ secrets.SSH_USER }}  # Nom d'utilisateur SSH
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Clé privée SSH
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $SSH_USER@$SERVER_IP << 'EOF'
            cd /chemin/de/ton/projet
            git pull origin main  # Récupérer les dernières modifications
            source venv/bin/activate  # Activer l'environnement virtuel
            pip install -r requirements.txt  # Installer les nouvelles dépendances
            systemctl restart mon_api  # Redémarrer l'API
          EOF
